name: Tagged Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-tagged-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
        id: get_tag
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - name: Bundle built files
        run: |
          mkdir -p ./temp/BendzDevtools
          cp ./{fxmanifest.lua,README.md,LICENSE} ./temp/bendz_banking/
          cp -r ./{dist,html,client,server} ./temp/bendz_banking
          cd ./temp && zip -r ../bendz_bankingV${{ steps.get_tag.outputs.VERSION_TAG }}.zip ./bendz_banking
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Bendz Banking - ${{ steps.get_tag.outputs.VERSION_TAG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: bendz_bankingV${{ steps.get_tag.outputs.VERSION_TAG }}.zip
        id: auto_release
          
